myproject/urls.py
from django.contrib import admin
#from django.conf.urls import url
from django.urls import path, include
from asesorias import views
from accounts import views as accounts_views

urlpatterns = [


    path('administrador/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),




    #path(r'^register', views.register), 
    #path('index', views.index),
    path('', accounts_views.index),
    path('login', accounts_views.login),
    path('buscar', accounts_views.buscar),
    path('profesorVista', accounts_views.vistaProfesor),
    path('alumnoVista', accounts_views.vistaAlumno),
    path('registro', accounts_views.registro),
    path('register', accounts_views.register),
    path('agregarAsesoria', views.mostrarCursos),
    path('guardarAsesoria', views.guardarAsesoria),
    path('listarAsesoria', views.listarAsesoria),
    path('eliminarAsesoria', views.eliminarAsesoria),
    path('editarAsesoria', views.editarAsesoria),
    path('guardarCambios', views.guardarCambios),
    path('cancelar', views.cancelar),
    path('salir', views.salir),
    path('logout', views.logout),
    path('generarCita', accounts_views.generarCita),
    path('consultarCita', accounts_views.consultarCita),
    path('alumnoCita', accounts_views.alumnoCita),
    path('regresar', accounts_views.regresar),
    path('cancelarCita', accounts_views.cancelarCita),
    path('marcarAtencion', accounts_views.marcarAtencion),

    path('validate_curso', accounts_views.validate_curso),
    path('validate_profesor', accounts_views.validate_profesor),
    path('obtenerFechaCita', accounts_views.obtenerFechaCita),


    path('citaAtendida', accounts_views.citaAtendida),
    path('feedback', accounts_views.feedback),
    path('citaFin', accounts_views.citaFin),
    path('regresarVistaProfe', accounts_views.regresarVistaProfe),

]

asesorias/models.py
from django.db import models
#from django.contrib.auth.models import User
from accounts.models import User
# Create your models here.

import datetime

class Curso(models.Model):
    #codigo = models.AutoField()
    nombre= models.CharField(max_length=255)
    creditos= models.IntegerField()
    nivel=models.IntegerField()


class Seccion(models.Model):
    codigo=models.IntegerField()
    curso=models.ForeignKey(Curso,on_delete=models.CASCADE)
    profesor=models.ForeignKey(User, on_delete=models.CASCADE)

class Asesoria(models.Model):
    #codigo = models.AutoField()
    dia= models.CharField(max_length=255)
    horario= models.CharField(max_length=255)
    lugar=models.CharField(max_length=255)
    seccion=models.ForeignKey(Seccion,on_delete=models.CASCADE,default='000')

class Cita(models.Model):
    asesoria=models.ForeignKey(Asesoria, on_delete=models.CASCADE)
    alumno=models.ForeignKey(User,on_delete=models.CASCADE)
    comentario=models.CharField(max_length=255, default='null')
    estado=models.BooleanField(default=True)
    archivo=models.CharField(max_length=255, default='null')
    feedback= models.CharField(max_length=255, default='null')
    fechaCita=models.DateTimeField(blank=True, null=True,default=datetime.date.today)

class FactTable(models.Model):
    curso=models.ForeignKey(Curso,on_delete=models.CASCADE, related_name = 'cursoFact')
    profesor=models.ForeignKey(User, on_delete=models.CASCADE, related_name = 'profesorFact')
    asesoria=models.ForeignKey(Asesoria, on_delete=models.CASCADE, related_name = 'asesoriaFact')
    seccion=models.ForeignKey(Seccion,on_delete=models.CASCADE,default='000', related_name = 'seccionFact')

templates/agregarAsesoria.html
{% extends 'index.html' %}
{% block javascript %}
  <script>
  $("#id_curso").change(function () {

      console.log($(this).val() );
      var curso=$(this).val()

      $.ajax({
           url: 'validate_curso',
           data: {
             'curso': curso
           },
           dataType: 'json',
           success: function (data) {
             var profes = JSON.parse(data.profesores);

              var $el = $("#id_profesor");
              $el.empty(); // remove old options
              $el.append($("<option></option>")
                 .attr("value", "Seleccione un profesor").text("Seleccione un profesor"));
              $.each(profes, function(key,value) {
                $el.append($("<option></option>")
                   .attr("value", value).text(value));
              });
           }
         });
       });
  $("#id_profesor").change(function () {
      console.log($(this).val() );
      var profesor=$(this).val();
      profe=profesor.split(" ")
      console.log("hollaaa  "+profe[1]);
      $.ajax({
           url: 'validate_profesor',
           data: {
             'first': profe[0],
             'last': profe[1]
           },
           dataType: 'json',
           success: function (data) {
             /*var secciones = JSON.parse(data.seccion );
             /*var codigos = JSON.parse(data.cod );*/
             var secciones=JSON.parse(data.seccion)
             /*console.log(secciones[0]);*/
             console.log();
              var $el = $("#id_seccion");
              $el.empty(); // remove old options
              $.each(secciones, function(key,value) {
                $el.append($("<option></option>")
                .attr("value", value).text(value));
              });

           }
         });
       });

  </script>
{% endblock %}
{% block content %}
<div class="container">
    <div class="row justify-content-center">
        <div class="col-4">
            <div class="card">
                <h4 class="card-header text-center">Agregar Asesoria</h4>
                <div class="card-block">
                    <form method="post" action="/guardarAsesoria">
                        {% csrf_token %}
                        <div class="form-group">
                            <label>Curso:</label>
                              <select name="curso" id="id_curso" class="form-group has-danger">
                                <option type="submit" value="Seleccione un curso">Seleccione un curso</option>
                                {% for item in curso %}
                                  <option type="submit" value="{{item.nombre}}">{{item.nombre}}</option>
                                {% endfor %}
                              </select>


                        </div>
                        <div class="form-group">
                            <label>Profesor:</label>
                              <select name="profesor"  id="id_profesor" class="form-group has-danger">

                                  <option type="submit" value="{{item.first_name}}">-</option>

                              </select>


                        </div>
                        <div class="form-group">
                            <label>Seccion:</label>
                              <select name="seccion" id="id_seccion"class="form-group has-danger">

                                  <option type="submit" value="{{item.codigo}}"></option>

                              </select>

                        </div>
                        <div class="form-group">
                            <label>Horario:</label>
                            <input name="horario" type="text" class="form-control">

                        </div>
                        <div class="form-group">
                            <label>Lugar:</label>
                            <input name="lugar" type="text" class="form-control">

                        </div>
                        <div class="form-group">
                            <label>Día:</label>
                            <select name="dia" class="form-group has-danger">
                              <option value="lunes">lunes</option>
                              <option value="martes">martes</option>
                              <option value="miercoles">miercoles</option>
                              <option value="jueves">jueves</option>
                              <option value="viernes">viernes</option>
                              <option value="sabado">sabado</option>
                            </select>
                        </div>
                        <div class="mx-auto text-center">
                            <input type="submit" value="Agregar" class="btn btn-primary">
                        </div>
                    </form>
                </div>
            </div>
        </div>
      </div>
  </div>

{% endblock %}

templates/agregarUsuario.html
{% extends 'index.html' %}
{% block content %}
<div class="container">
    <div class="row justify-content-center">
      <div class="col-4">
          <div class="card">
              <h4 class="card-header text-center">Register</h4>
              <div class="card-block">
                  <form method="post" action="/register">
                      {% csrf_token %}
                      <div class="form-group">
                          <label>First Name</label>
                          <input name="first_name" type="text" class="form-control form-control-danger">
                          {% if messages %}
                          {%for message in messages %}
                          {%if "first_name" in message.tags %}
                          <div class="form-group has-danger">
                              <div class="form-control-feedback">{{message}}</div>
                            </div>
                          {%endif%} {%endfor%} {% endif %}
                      </div>
                      <div class="form-group">
                          <label>Last Name</label>
                          <input name="last_name" type="text" class="form-control">
                          {% if messages %}
                          {%for message in messages %}
                          {%if "last_name" in message.tags %}
                          <div class="form-group has-danger">
                              <div class="form-control-feedback">{{message}}</div>
                            </div>
                          {%endif%} {%endfor%} {% endif %}
                      </div>
                      <div class="form-group">
                          <label>Email</label>
                          <input name="email" type="email" class="form-control">
                          {% if messages %}
                          {%for message in messages %}
                          {%if "email" in message.tags %}
                          <div class="form-group has-danger">
                              <div class="form-control-feedback">{{message}}</div>
                            </div>
                          {%endif%} {%endfor%} {% endif %}
                      </div>
                      <div class="form-group">
                          <label>Password</label>
                          <input name="password" type="password" class="form-control">
                          {% if messages %}
                          {%for message in messages %}
                          {%if "password" in message.tags %}
                          <div class="form-group has-danger">
                              <div class="form-control-feedback">{{message}}</div>
                            </div>
                          {%endif%} {%endfor%} {% endif %}
                      </div>
                      <div class="form-group">
                          <label>Confirm Password</label>
                          <input name="confirm_password" type="password" class="form-control">
                          {% if messages %}
                          {%for message in messages %}
                          {%if "confirm_password" in message.tags %}
                          <div class="form-group has-danger">
                              <div class="form-control-feedback">{{message}}</div>
                            </div>
                          {%endif%} {%endfor%} {% endif %}
                      </div>
                      <div class="form-group">
                          <label>Tipo de usuario</label>
                          <select name="nyc">
                          	<option value="profesor">Profesor</option>
                          	<option value="admin">Administrador</option>
                          	<option value="alumno">Alumno</option>
                          </select>
                          {% if messages %}
                          {%for message in messages %}
                          {%if "confirm_password" in message.tags %}
                          <div class="form-group has-danger">
                              <div class="form-control-feedback">{{message}}</div>
                            </div>
                          {%endif%} {%endfor%} {% endif %}
                      </div>
                      <div class="mx-auto text-center">
                          <input type="submit" value="Create Account" class="btn btn-primary">
                      </div>
                  </form>
              </div>
          </div>
          <div class="mx-auto text-center">
            <p></p>
            <a href="/salir" class="btn btn-danger">Salir</a>
          </div>
      </div>
    </div>
  </div>
  {% endblock %}

templates/alumnoCita.html
{% load static %}<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>{% block title %}ULima Citas{% endblock %}</title>
  <link href="https://fonts.googleapis.com/css?family=Peralta" rel="stylesheet">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ"crossorigin="anonymous">
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>
  <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous"/>
</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
      <a class="navbar-brand" href="">Bienvenido, {{ nombreAlumno.first_name }} {{ nombreAlumno.last_name}}</a>
    </div>
    <p></p>
    <div align="center">
      <h2>Citas</h2>
    </div>
  </nav>

  <div class="container">
    <div>
      <form action="/logout" method="post">
      {% csrf_token %}
        <button type="submit" name="logout" class="btn btn-danger">Logout</button>
      </form>
    </div>
    <p></p>
    <div align="right">
      <form action="/citaAtendida" method='get'>
      {% csrf_token %}
        <button class="btn btn-primary" type="submit" name="citaAtendida">Citas Atendidas</button>
      </form>
    </div>
    <p></p>
    <div align="right">
      <form action="/regresar" method='get'>
      {% csrf_token %}
        <button class="btn btn-warning" type="submit" name="regresar">Regresar</button>
      </form>
    </div>
    <p></p>

  <table class="table">
    <thead class="thead-inverse">
      <tr>
        <th></th>
        <th>Curso</th>
        <th>Profesor</th>
        <th>Horario</th>
        <th>Lugar</th>
        <th>Día</th>
        <th>Sección</th>
        <th>Comentario</th>
        <th>Fecha</th>
        <th>Archivo</th>
        <th>Operación</th>
      </tr>
    </thead>
    <tbody>
      {% for item in arreglo %}
        <form action="/cancelarCita" method="post">
        {% csrf_token %}
          <tr>
            <th><input type= "hidden" name="id_cita" value= {{ item.id }}></th>
            <th>{{ item.curso }}</th>
            <th>{{ item.profesor }}</th>
            <th>{{ item.horario }}</th>
            <th>{{ item.lugar }}</th>
            <th>{{ item.dia }}</th>
            <th>{{ item.seccion }}</th>
            <th>{{ item.comentario }}</th>
            <th>{{ item.fechaCita|date:'Y-m-d' }}</th>
            {% ifequal item.archivo 0 %}
              {% csrf_token %}
              <th>No hay archivo</th>
              <th><button class="btn btn-danger" type="submit" name="cancelarCita">Cancelar Cita</button></th>
            {%else%}
            {% csrf_token %}
              <th><a href="{{ item.archivo }}">Descargar<i class="fa fa-cloud-download"></i></a></th>
              <th><button class="btn btn-danger" type="submit" name="cancelarCita">Cancelar Cita</button></th>
            {% endifequal %}
          </tr>
        </form>
      {% endfor %}
    </tbody>
  </table>

</div>
</body>
</html>

templates/alumnoVista.html
{% load static %}<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>{% block title %}Vista de Alumno{% endblock %}</title>
  <link href="https://fonts.googleapis.com/css?family=Peralta" rel="stylesheet">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ"crossorigin="anonymous">
  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>
  <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous"/>
  <link href = "https://code.jquery.com/ui/1.10.4/themes/ui-lightness/jquery-ui.css"rel = "stylesheet">

  <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js" integrity="sha384-b/U6ypiBEHpOf/4+1nzFpr53nxSS+GLCkfwBdFNTxtclqqenISfwAzpKaMNFNmj4" crossorigin="anonymous"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js" integrity="sha384-h0AbiXch4ZDo7tp9hKZ4TsHbi047NrKGLO3SEJAg45jXxnGIfYzk4Si90RDIqNm1" crossorigin="anonymous"></script>


   <style>
   </style>

</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
      <a class="navbar-brand" href="">Bienvenido, {{ nombreAlumno.first_name }} {{ nombreAlumno.last_name}}</a>
    </div>
    <p></p>
    <div align="center">
      <h2>Asesorias ULima</h2>
    </div>
  </nav>

  <div class="container">
    <div>
      <form action="/logout" method="post">
        {% csrf_token %}
        <button type="submit" name="logout" class="btn btn-danger">Logout</button>
      </form>
    </div>
    <ol class="breadcrumb my-4">
      <div>
        <form action="/buscar" method="POST">
          {% csrf_token %}
          <input type="text" name="buscar" >
          <button type="submit" class="btn">Search</button>
        </form>
        <form action="/alumnoVista" method="POST">
          {% csrf_token %}
          <button type="submit" class="btn">Reset</button>
        </form>
      </div>

    </ol>
    <div align="right">
      <form action="/consultarCita" method="get">
        {% csrf_token %}
        <button class="btn btn-warning" type="submit" name="consultarCita">Consultar Citas</button>
      </form>
    </div>
    <p></p>
    <table class="table">
      <thead class="thead-inverse">
        <tr>
          <th></th>
          <th>Curso</th>
          <th>Profesor</th>
          <th>Horario</th>
          <th>Lugar</th>
          <th>Día</th>
          <th>Sección</th>
          <th>Operación</th>
        </tr>
      </thead>
      <tbody>
        {% for item in arreglo %}


          <tr>
            <th><input type= "hidden" name="id_asesoria" value= {{item.id}}></th>
            <th>{{ item.curso }}</th>
            <th>{{ item.profesor }}</th>
            <th>{{ item.horario }}</th>
            <th>{{ item.lugar }}</th>
            <th>{{ item.dia }}</th>
            <th>{{ item.seccion }}</th>
            <th>
              <a href="#" id="id_modal" data-toggle="modal" data-target=".bd-example-modal-lg{{item.id}}"> Agendar Cita <i  class="fa fa-pencil-square-o"></i> </a>
            </th>
          </tr>
        {% endfor %}
          </div>
        {% for item in arreglo %}


              <form enctype="multipart/form-data" class="" action="/generarCita" method="post">
                {% csrf_token %}
          <div class="modal fade bd-example-modal-lg{{item.id}}" tabindex="-1" role="dialog" aria-labelledby="myLargeModalLabel" aria-hidden="true">
            <div class="modal-dialog modal-lg">
              <input type= "hidden" name="id_asesoria" value= {{ item.id }}>
              <div class="modal-content">
                <div class="modal-header">
                  <h2 class="modal-title">Generar Cita</h2>
                  <button type="button" class="close" data-dismiss="modal">&times;</button>
                </div>
                <div class="modal-body">
                  <div class="container-fluid">
                    <div class="row">
                      <div class="col-sm-6">
                        <h4>Datos de la asesoría</h4>
                        {% ifequal citaGenerada True %}
                          {% csrf_token %}
                          <div class="">
                            Ya existe una cita generada
                          </div>
                            {% endifequal %}
                              <select class="semana" data-tag="{{item.dia}}"id="numSemana/{{item.id}}">
                                <option value="seleccion">Selecciona una semana</option>
                                <option value="sem/1">Semana 1</option>
                                <option value="sem/2">Semana 2</option>
                                <option value="sem/3">Semana 3</option>
                                <option value="sem/4">Semana 4</option>
                                <option value="sem/5">Semana 5</option>
                                <option value="sem/6">Semana 6</option>
                                <option value="sem/7">Semana 7</option>
                                <option value="sem/8">Semana 8</option>
                                <option value="sem/9">Semana 9</option>
                                <option value="sem/10">Semana 10</option>
                                <option value="sem/11">Semana 11</option>
                                <option value="sem/12">Semana 12</option>
                                <option value="sem/13">Semana 13</option>
                                <option value="sem/14">Semana 14</option>
                                <option value="sem/15">Semana 15</option>
                                <option value="sem/16">Semana 16</option>

                              </select>
                              <br>
                              <br>
                              <ul hidden=True style= "list-style-type:none" id="fechaCita{{item.id}}">
                                <li><medium>Curso: {{ item.curso}} </medium></li>
                                <li><medium>Profesor: {{ item.profesor }} </medium></li>
                                <li><medium>Seccion: {{ item.seccion }} </medium></li>
                                <li><medium>Lugar: {{ item.lugar }} </medium></li>
                                <li><medium>Día: {{item.dia }} </medium></li>
                                <li><medium id="opcion{{item.id}}">Fecha:  </medium></li>
                                <input hidden=True name ="fecha_pactada"  type="text" id="input{{item.id}}" name="fecha_pactada" >
                              </ul>


                          </div>

                      <div class="col-sm-6">
                        <h5>Comentario</h5>
                        <textarea  name="comentario" rows="5" cols="40" >
                        </textarea>
                        <div >

                    	      <input type="file" class="filestyle" name="file"data-buttonText="Select a File">

                        </div>
                        <button class="btn btn-primary" type="submit" name="generarCita">Generar Cita</button>

                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
          </div>

      </form>
        {% endfor %}
    </tbody>
  </table>
  <script src="https://code.jquery.com/jquery-3.1.0.min.js"></script>

  <script type="text/javascript">
  $('.semana').each(function(i, obj) {
    //test

  $(this).change(function (event) {

    console.log($(this).val() );
    var semana=$(this).val()
    var id=event.target.id
    var itemId=id.split("/")
    var item=itemId[1]
    var diaSemana=event.target.attributes.getNamedItem('data-tag').value
    var a=3
    alert(item)
    alert(id)
    alert(semana)
    alert(diaSemana)
    $.ajax({

         url: 'obtenerFechaCita',
         data: {
           'numSemana': semana,
           'idSemana':id,
           'diaSemana':diaSemana
         },
         dataType: 'json',
         success: function (data) {
           console.log(data.fecha);
           var $el = $("#fechaCita"+item);
           console.log("esto es "+ a);
            $el.removeAttr('hidden');
            /*$el.append($("<li><medium></medium></li>").attr("name", "Fecha123").text("Fecha: "+data.fecha));
            */
            var $mod = $("#opcion"+item);
            $mod.text("Fecha: "+data.fecha);
           console.log("paso");

           var $inp = $("#input"+item);
           $inp.attr("value",data.fecha);
          console.log("paso");
           /*
           console.log("Fin de semana");
           var profes = JSON.parse(data.profesores);
              var $el = $("#id_profesor");
            $el.empty(); // remove old options
            $el.append($("<option></option>")
               .attr("value", "Seleccione un profesor").text("Seleccione un profesor"));
            $.each(profes, function(key,value) {
              $el.append($("<option></option>")
                 .attr("value", value).text(value));
              });*/
           }
         });
       });
});
  </script>
</body>
</html>

templates/citaFin.html
{% load static %}<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <title>{% block title %}Vista de Profesor{% endblock %}</title>
  <link href="https://fonts.googleapis.com/css?family=Peralta" rel="stylesheet">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ"
  crossorigin="anonymous">

</head>
<body>
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
      <a class="navbar-brand" href="">Bienvenido, {{ nombreProfesor.first_name }} {{ nombreProfesor.last_name}}</a>
    </div>
    <p></p>
    <div align="center">
      <h2>Citas Finalizadas</h2>
    </div>
  </nav>

  <div class="container">
    <div>
      <form action="/logout" method="post">
      {% csrf_token %}
        <button type="submit" name="logout" class="btn btn-danger">Logout</button>
      </form>
    </div>

    <div align="right">
      <form action="/regresarVistaProfe" method='get'>
      {% csrf_token %}
        <button class="btn btn-warning" type="submit" name="regresarVistaProfe">Regresar</button>
      </form>
    </div>
    <p></p>

  <table class="table">
    <thead class="thead-inverse">
      <tr>
        <th></th>
        <th>Curso</th>
        <th>Alumno</th>
        <th>Horario</th>
        <th>Lugar</th>
        <th>Día</th>
        <th>Sección</th>
        <th>Comentario</th>
        <th>Feedback</th>
      </tr>
    </thead>
    <tbody>
      {% for item in arreglo %}
          <tr>
            <th><input type= "hidden" name="id_cita" value= {{ item.id }}></th>
            <th>{{ item.curso }}</th>
            <th>{{ item.alumno }}</th>
            <th>{{ item.horario }}</th>
            <th>{{ item.lugar }}</th>
            <th>{{ item.dia }}</th>
            <th>{{ item.seccion }}</th>
            <th>{{ item.comentario }}</th>
            {% ifequal item.feedback expresion %}
            <th>-</th>
            {% else %}
            <th>{{ item.feedback }}</th>
            {% endifequal %}
      {% endfor %}
    </tbody>
  </table>

</div>
</body>
</html>